
##Include branch 'main'
trigger:
  branches:
    include:
      - "main"

pool:
  vmImage: ubuntu-latest

variables:
  - group: az-foundations-level-one

stages:
  - stage: GoBuildTest
    displayName: Go Build And Test
    jobs:
      - job: GoTestBuild
        displayName: Running Go Tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              go version 
              go env
              go install 
              go build .
              ./net_spaces address --cidr /26 --region westus2 --size venti --space 10.220.0.0
              go test -v ./...
            displayName: Go Version and Go Build
            env:
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

