
##Include branch 'main'
trigger:
  branches:
    include:
      - "main"

pool:
  vmImage: ubuntu-latest

variables:
  - group: az-foundations-level-one

stages:
  - stage: GoBuildTest
    displayName: Go Build And Test
    jobs:
      - job: GoTestBuild
        displayName: Running Go Tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              go version 
              go env
              go install 
              go build -v ./...
              go test -v ./...
              chmod +x ./net_spaces
              ./net_spaces address --cidr /26 --region westus2 --size venti --space 10.220.0.0
            displayName: Go Version and Go Build

