
##Include branch 'main'
trigger:
  branches:
    include:
      - "main"

pool:
  vmImage: ubuntu-latest

variables:
  - group: az-foundations-level-one

stages:
  - stage: GoBuildTest
    displayName: Go Build And Test
    jobs:
      - job: GoTestBuild
        displayName: Running Go Tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              go version 
              go env
              go install 
              ls ~/go/bin 
              export PATH=$PATH:~/go/bin
            displayName: Go Version and Go Build

